/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HangarRouteImport } from './routes/hangar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMaintenanceCasesRouteImport } from './routes/api/maintenance-cases'

const HangarRoute = HangarRouteImport.update({
  id: '/hangar',
  path: '/hangar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMaintenanceCasesRoute = ApiMaintenanceCasesRouteImport.update({
  id: '/api/maintenance-cases',
  path: '/api/maintenance-cases',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hangar': typeof HangarRoute
  '/api/maintenance-cases': typeof ApiMaintenanceCasesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hangar': typeof HangarRoute
  '/api/maintenance-cases': typeof ApiMaintenanceCasesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hangar': typeof HangarRoute
  '/api/maintenance-cases': typeof ApiMaintenanceCasesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hangar' | '/api/maintenance-cases'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hangar' | '/api/maintenance-cases'
  id: '__root__' | '/' | '/hangar' | '/api/maintenance-cases'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HangarRoute: typeof HangarRoute
  ApiMaintenanceCasesRoute: typeof ApiMaintenanceCasesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/hangar': {
      id: '/hangar'
      path: '/hangar'
      fullPath: '/hangar'
      preLoaderRoute: typeof HangarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/maintenance-cases': {
      id: '/api/maintenance-cases'
      path: '/api/maintenance-cases'
      fullPath: '/api/maintenance-cases'
      preLoaderRoute: typeof ApiMaintenanceCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HangarRoute: HangarRoute,
  ApiMaintenanceCasesRoute: ApiMaintenanceCasesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
