/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as HangarRouteImport } from './routes/hangar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as HangarIndexRouteImport } from './routes/hangar.index'
import { Route as StaffNewRouteImport } from './routes/staff.new'
import { Route as StaffStaffIdRouteImport } from './routes/staff.$staffId'
import { Route as HangarNewRouteImport } from './routes/hangar.new'
import { Route as HangarCaseIdRouteImport } from './routes/hangar.$caseId'
import { Route as ApiStaffRouteImport } from './routes/api.staff'
import { Route as ApiMaintenanceCasesRouteImport } from './routes/api.maintenance-cases'
import { Route as ApiMaintenanceCaseStaffRouteImport } from './routes/api.maintenance-case-staff'
import { Route as ApiElectricStaffRouteImport } from './routes/api.electric.staff'
import { Route as ApiElectricMaintenanceCasesRouteImport } from './routes/api.electric.maintenance-cases'
import { Route as ApiElectricMaintenanceCaseStaffRouteImport } from './routes/api.electric.maintenance-case-staff'

const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const HangarRoute = HangarRouteImport.update({
  id: '/hangar',
  path: '/hangar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const HangarIndexRoute = HangarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HangarRoute,
} as any)
const StaffNewRoute = StaffNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => StaffRoute,
} as any)
const StaffStaffIdRoute = StaffStaffIdRouteImport.update({
  id: '/$staffId',
  path: '/$staffId',
  getParentRoute: () => StaffRoute,
} as any)
const HangarNewRoute = HangarNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => HangarRoute,
} as any)
const HangarCaseIdRoute = HangarCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => HangarRoute,
} as any)
const ApiStaffRoute = ApiStaffRouteImport.update({
  id: '/api/staff',
  path: '/api/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMaintenanceCasesRoute = ApiMaintenanceCasesRouteImport.update({
  id: '/api/maintenance-cases',
  path: '/api/maintenance-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMaintenanceCaseStaffRoute = ApiMaintenanceCaseStaffRouteImport.update({
  id: '/api/maintenance-case-staff',
  path: '/api/maintenance-case-staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElectricStaffRoute = ApiElectricStaffRouteImport.update({
  id: '/api/electric/staff',
  path: '/api/electric/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElectricMaintenanceCasesRoute =
  ApiElectricMaintenanceCasesRouteImport.update({
    id: '/api/electric/maintenance-cases',
    path: '/api/electric/maintenance-cases',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiElectricMaintenanceCaseStaffRoute =
  ApiElectricMaintenanceCaseStaffRouteImport.update({
    id: '/api/electric/maintenance-case-staff',
    path: '/api/electric/maintenance-case-staff',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hangar': typeof HangarRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/api/maintenance-case-staff': typeof ApiMaintenanceCaseStaffRoute
  '/api/maintenance-cases': typeof ApiMaintenanceCasesRoute
  '/api/staff': typeof ApiStaffRoute
  '/hangar/$caseId': typeof HangarCaseIdRoute
  '/hangar/new': typeof HangarNewRoute
  '/staff/$staffId': typeof StaffStaffIdRoute
  '/staff/new': typeof StaffNewRoute
  '/hangar/': typeof HangarIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/api/electric/maintenance-case-staff': typeof ApiElectricMaintenanceCaseStaffRoute
  '/api/electric/maintenance-cases': typeof ApiElectricMaintenanceCasesRoute
  '/api/electric/staff': typeof ApiElectricStaffRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/maintenance-case-staff': typeof ApiMaintenanceCaseStaffRoute
  '/api/maintenance-cases': typeof ApiMaintenanceCasesRoute
  '/api/staff': typeof ApiStaffRoute
  '/hangar/$caseId': typeof HangarCaseIdRoute
  '/hangar/new': typeof HangarNewRoute
  '/staff/$staffId': typeof StaffStaffIdRoute
  '/staff/new': typeof StaffNewRoute
  '/hangar': typeof HangarIndexRoute
  '/staff': typeof StaffIndexRoute
  '/api/electric/maintenance-case-staff': typeof ApiElectricMaintenanceCaseStaffRoute
  '/api/electric/maintenance-cases': typeof ApiElectricMaintenanceCasesRoute
  '/api/electric/staff': typeof ApiElectricStaffRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hangar': typeof HangarRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/api/maintenance-case-staff': typeof ApiMaintenanceCaseStaffRoute
  '/api/maintenance-cases': typeof ApiMaintenanceCasesRoute
  '/api/staff': typeof ApiStaffRoute
  '/hangar/$caseId': typeof HangarCaseIdRoute
  '/hangar/new': typeof HangarNewRoute
  '/staff/$staffId': typeof StaffStaffIdRoute
  '/staff/new': typeof StaffNewRoute
  '/hangar/': typeof HangarIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/api/electric/maintenance-case-staff': typeof ApiElectricMaintenanceCaseStaffRoute
  '/api/electric/maintenance-cases': typeof ApiElectricMaintenanceCasesRoute
  '/api/electric/staff': typeof ApiElectricStaffRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hangar'
    | '/staff'
    | '/api/maintenance-case-staff'
    | '/api/maintenance-cases'
    | '/api/staff'
    | '/hangar/$caseId'
    | '/hangar/new'
    | '/staff/$staffId'
    | '/staff/new'
    | '/hangar/'
    | '/staff/'
    | '/api/electric/maintenance-case-staff'
    | '/api/electric/maintenance-cases'
    | '/api/electric/staff'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/maintenance-case-staff'
    | '/api/maintenance-cases'
    | '/api/staff'
    | '/hangar/$caseId'
    | '/hangar/new'
    | '/staff/$staffId'
    | '/staff/new'
    | '/hangar'
    | '/staff'
    | '/api/electric/maintenance-case-staff'
    | '/api/electric/maintenance-cases'
    | '/api/electric/staff'
  id:
    | '__root__'
    | '/'
    | '/hangar'
    | '/staff'
    | '/api/maintenance-case-staff'
    | '/api/maintenance-cases'
    | '/api/staff'
    | '/hangar/$caseId'
    | '/hangar/new'
    | '/staff/$staffId'
    | '/staff/new'
    | '/hangar/'
    | '/staff/'
    | '/api/electric/maintenance-case-staff'
    | '/api/electric/maintenance-cases'
    | '/api/electric/staff'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HangarRoute: typeof HangarRouteWithChildren
  StaffRoute: typeof StaffRouteWithChildren
  ApiMaintenanceCaseStaffRoute: typeof ApiMaintenanceCaseStaffRoute
  ApiMaintenanceCasesRoute: typeof ApiMaintenanceCasesRoute
  ApiStaffRoute: typeof ApiStaffRoute
  ApiElectricMaintenanceCaseStaffRoute: typeof ApiElectricMaintenanceCaseStaffRoute
  ApiElectricMaintenanceCasesRoute: typeof ApiElectricMaintenanceCasesRoute
  ApiElectricStaffRoute: typeof ApiElectricStaffRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hangar': {
      id: '/hangar'
      path: '/hangar'
      fullPath: '/hangar'
      preLoaderRoute: typeof HangarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/hangar/': {
      id: '/hangar/'
      path: '/'
      fullPath: '/hangar/'
      preLoaderRoute: typeof HangarIndexRouteImport
      parentRoute: typeof HangarRoute
    }
    '/staff/new': {
      id: '/staff/new'
      path: '/new'
      fullPath: '/staff/new'
      preLoaderRoute: typeof StaffNewRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/$staffId': {
      id: '/staff/$staffId'
      path: '/$staffId'
      fullPath: '/staff/$staffId'
      preLoaderRoute: typeof StaffStaffIdRouteImport
      parentRoute: typeof StaffRoute
    }
    '/hangar/new': {
      id: '/hangar/new'
      path: '/new'
      fullPath: '/hangar/new'
      preLoaderRoute: typeof HangarNewRouteImport
      parentRoute: typeof HangarRoute
    }
    '/hangar/$caseId': {
      id: '/hangar/$caseId'
      path: '/$caseId'
      fullPath: '/hangar/$caseId'
      preLoaderRoute: typeof HangarCaseIdRouteImport
      parentRoute: typeof HangarRoute
    }
    '/api/staff': {
      id: '/api/staff'
      path: '/api/staff'
      fullPath: '/api/staff'
      preLoaderRoute: typeof ApiStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/maintenance-cases': {
      id: '/api/maintenance-cases'
      path: '/api/maintenance-cases'
      fullPath: '/api/maintenance-cases'
      preLoaderRoute: typeof ApiMaintenanceCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/maintenance-case-staff': {
      id: '/api/maintenance-case-staff'
      path: '/api/maintenance-case-staff'
      fullPath: '/api/maintenance-case-staff'
      preLoaderRoute: typeof ApiMaintenanceCaseStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/electric/staff': {
      id: '/api/electric/staff'
      path: '/api/electric/staff'
      fullPath: '/api/electric/staff'
      preLoaderRoute: typeof ApiElectricStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/electric/maintenance-cases': {
      id: '/api/electric/maintenance-cases'
      path: '/api/electric/maintenance-cases'
      fullPath: '/api/electric/maintenance-cases'
      preLoaderRoute: typeof ApiElectricMaintenanceCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/electric/maintenance-case-staff': {
      id: '/api/electric/maintenance-case-staff'
      path: '/api/electric/maintenance-case-staff'
      fullPath: '/api/electric/maintenance-case-staff'
      preLoaderRoute: typeof ApiElectricMaintenanceCaseStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HangarRouteChildren {
  HangarCaseIdRoute: typeof HangarCaseIdRoute
  HangarNewRoute: typeof HangarNewRoute
  HangarIndexRoute: typeof HangarIndexRoute
}

const HangarRouteChildren: HangarRouteChildren = {
  HangarCaseIdRoute: HangarCaseIdRoute,
  HangarNewRoute: HangarNewRoute,
  HangarIndexRoute: HangarIndexRoute,
}

const HangarRouteWithChildren =
  HangarRoute._addFileChildren(HangarRouteChildren)

interface StaffRouteChildren {
  StaffStaffIdRoute: typeof StaffStaffIdRoute
  StaffNewRoute: typeof StaffNewRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffStaffIdRoute: StaffStaffIdRoute,
  StaffNewRoute: StaffNewRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HangarRoute: HangarRouteWithChildren,
  StaffRoute: StaffRouteWithChildren,
  ApiMaintenanceCaseStaffRoute: ApiMaintenanceCaseStaffRoute,
  ApiMaintenanceCasesRoute: ApiMaintenanceCasesRoute,
  ApiStaffRoute: ApiStaffRoute,
  ApiElectricMaintenanceCaseStaffRoute: ApiElectricMaintenanceCaseStaffRoute,
  ApiElectricMaintenanceCasesRoute: ApiElectricMaintenanceCasesRoute,
  ApiElectricStaffRoute: ApiElectricStaffRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
